application: issue-tracker-robot
version: 1
runtime: python
api_version: 1

handlers:

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /_wave/.*
  script: robot.py

- url: /web
  script: main.py

- url: .*
  script: main.py
